# Generated by Django 2.2.6 on 2019-10-09 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('common_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OngoingMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id_64', models.IntegerField()),
                ('steam_id_3', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FinishedMatch',
            fields=[
                ('ongoingmatch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='league_analysis.OngoingMatch')),
            ],
            bases=('league_analysis.ongoingmatch',),
        ),
        migrations.CreateModel(
            name='TeamRollingStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_kills', models.FloatField()),
                ('average_deaths', models.FloatField()),
                ('average_assists', models.FloatField()),
                ('average_kda', models.FloatField()),
                ('matches_played', models.IntegerField()),
                ('matches_won', models.IntegerField()),
                ('series_played', models.IntegerField()),
                ('series_won', models.IntegerField()),
                ('average_creep_stats', models.FloatField()),
                ('average_xpm', models.FloatField()),
                ('average_gpm', models.FloatField()),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='league_analysis.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHeroPickStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField()),
                ('win_count', models.IntegerField()),
                ('win_percent', models.FloatField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_stats', to='league_analysis.Hero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hero_stats', to='league_analysis.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRollingStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_kills', models.FloatField()),
                ('average_deaths', models.FloatField()),
                ('average_assists', models.FloatField()),
                ('average_kda', models.FloatField()),
                ('creep_stats_average', models.FloatField()),
                ('xpm_average', models.FloatField()),
                ('gpm_average', models.FloatField()),
                ('most_common_role', models.CharField(max_length=2)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='league_analysis.Player')),
            ],
        ),
        migrations.AddField(
            model_name='ongoingmatch',
            name='team_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_first_team', to='league_analysis.Team'),
        ),
        migrations.AddField(
            model_name='ongoingmatch',
            name='team_one_players',
            field=models.ManyToManyField(related_name='matches_on_first_team', to='league_analysis.Player'),
        ),
        migrations.AddField(
            model_name='ongoingmatch',
            name='team_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='matches_as_second_team', to='league_analysis.Team'),
        ),
        migrations.AddField(
            model_name='ongoingmatch',
            name='team_two_players',
            field=models.ManyToManyField(related_name='matches_on_second_team', to='league_analysis.Player'),
        ),
    ]
