# Generated by Django 2.2.6 on 2019-10-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_analysis', '0002_auto_20191008_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerrollingstatistics',
            old_name='creep_stats_average',
            new_name='average_creep_stats',
        ),
        migrations.RenameField(
            model_name='playerrollingstatistics',
            old_name='gpm_average',
            new_name='average_gpm',
        ),
        migrations.RenameField(
            model_name='playerrollingstatistics',
            old_name='xpm_average',
            new_name='average_xpm',
        ),
        migrations.AlterField(
            model_name='teamheropickstatistics',
            name='pick_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamheropickstatistics',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamheropickstatistics',
            name='win_percent',
            field=models.FloatField(default=0),
        ),
    ]
