# Generated by Django 2.2.6 on 2019-10-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_analysis', '0003_auto_20191010_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_image_url',
            field=models.CharField(default='https://i.imgur.com/JYuNKXp.jpg', max_length=600),
        ),
    ]
